[JBWS-4430]:Sever throws IllegalStateException when call a handler wi…
jbossws/jbossws-cxf pull request #557
Opened 2024-10-21 12:24 UTC by jimma

…th the CDI bean invocation

2024-10-21 13:50 UTC, asoldano requested changes
hi @jimma , when this will be ready (in general, not just wrt my other comments here), please be sure to include a testcase to cover this new scenario. Thanks!

2024-10-21 13:50 UTC, asoldano commented on modules/server/src/main/java/org/jboss/wsf/stack/cxf/interceptor/HandlerAuthInterceptor.java
> +   private boolean skipAuth = false;
Consider making this `final` if possible:
`private boolean skipAuth;`

and then you set that field in both constructors.

2024-10-21 13:50 UTC, asoldano commented on modules/server/src/main/java/org/jboss/wsf/stack/cxf/interceptor/HandlerAuthInterceptor.java
> +      private boolean skipAuth = false;
same as above regarding being `final`

2024-10-22 06:44 UTC, jimma commented
> hi @jimma , when this will be ready (in general, not just wrt my other comments here), please be sure to include a testcase to cover this new scenario. Thanks!

Yes. That is on my todo list.

2024-10-31 09:30 UTC, asoldano approved these changes
Thanks Jim, this looks ok, I've added a couple of minor comments.
WRT the AbstractTCCLPhaseInterceptor, I'm wondering if you explored the possibility of configuring that automatically by interjecting the creation of the interceptor chain in a modified PhaseInterceptorChain which could decide to wrap configured interceptors. Just a thought though, I haven't really verified / tested anything ;-)

2024-11-01 05:56 UTC, jimma commented on modules/server/src/main/java/org/jboss/wsf/stack/cxf/interceptor/HandlerAuthInterceptor.java
> +    * Please see
Fixed. Thanks.

2024-11-01 06:05 UTC, jimma commented
> Thanks Jim, this looks ok, I've added a couple of minor comments. WRT the AbstractTCCLPhaseInterceptor, I'm wondering if you explored the possibility of configuring that automatically by interjecting the creation of the interceptor chain in a modified PhaseInterceptorChain which could decide to wrap configured interceptors. Just a thought though, I haven't really verified / tested anything ;-)

@asoldano  Yes. I tried with checking the classloader and by adding set TCCL with interceptor.getClass().getClassLoader() in PhaseInterceptorChain for each interceptor before the interceptor call,  but this will slows down the performance. The current approach is more efficient as we need to set TCCL only for the interceptor which has CDI access.

2024-11-05 07:56 UTC, merged